config/routes.rb
Project1::Application.routes.draw do

  resources :teacher
  devise_for :users
  devise_for :users do get '/users/sign_out' => 'devise/sessions#destroy' end	

  match "home/feel"=>"home#feel"  
  match "home/goal"=>"home#goal"
  match "home/error"=>"home#error"
  match "home/activity"=>"home#activity"
  match "home/dreamcoffee"=>"home#dreamcoffee"
  match "home/aboutus"=>"home#aboutus"
  post "home/savediscuss"=>"home#savediscuss"
  root :to => "home#index"
  resources :home

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :name, :context, :feedback_id, :updated_at

  belongs_to :feedback
end

app/models/discuss.rb
class Discuss < ActiveRecord::Base
  attr_accessible :name, :phone, :email, :context, :feedback_id, :updated_at


  belongs_to :feedback
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
   attr_accessible :name, :phone, :email, :topic, :context, :replyto, :updated_at

   validates_presence_of :topic, :context
  
   has_many :answers
   has_many :discusses
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end

	def test
	end

	def goal
	end

	def aboutus
	end

	def error
	end

	def feel
	end

	def dreamcoffee
	end

	def activity
	end
	
	def new
		@showFeedbacks = Feedback.all		
	end

	def create
		params[:feedback][:context]=params[:feedback][:context].gsub(/\r\n?/, "\n")
		@feedback = Feedback.new(params[:feedback])
		if @feedback.save
			Sendmail.confirm("hhhb888@gmail.com",params[:feedback][:context]).deliver
			redirect_to new_home_path
		else
    			redirect_to home_error_path
		end
	end
	
	def show
		
		@id = params[:id]
		@showFeedbackContext = Feedback.find(@id)	
		@showAnswerContext = Feedback.find(@id).answers.all
		@showDiscussContext = Feedback.find(@id).discusses.all
	end

	def savediscuss
		params[:discuss][:context]=params[:discuss][:context].gsub(/\r\n?/, "\n")
		@discuss = Discuss.new(params[:discuss])
                @discuss.save
		redirect_to home_path(params[:discuss][:feedback_id])
	end

end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
	before_filter :authenticate_user!
	def index
	end

	def new
		@showFeedbacks = Feedback.all
	end

	def create
		params[:answer][:context]=params[:answer][:context].gsub(/\r\n?/, "\n")
		@answer = Answer.new(params[:answer])
                @answer.save

                redirect_to teacher_path(params[:answer][:feedback_id])
	end

	def show
		@id = params[:id]
                @showFeedbackContext = Feedback.find(@id)
                @showAnswerContext = Feedback.find(@id).answers.all
                @showDiscussContext = Feedback.find(@id).discusses.all        
	end

	def edit
  		@answer = Answer.find(params[:id])
	end

	def update
  		@answer = Answer.find(params[:id])
		params[:answer][:context]=params[:answer][:context].gsub(/\r\n?/, "\n")
  		@answer.update_attributes!(params[:answer])
  		flash[:notice] = "#{@answer.context} was successfully updated."
  		redirect_to teacher_path(@answer.feedback_id)
	end

	def destroy
  		@deleteFeedback = Feedback.find(params[:id])
  		@deleteFeedback.destroy
  		redirect_to new_teacher_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper
end

app/views/home/aboutus.html.erb
<div style="width:900px; margin: 0 auto;">
        <h2><font face="微軟正黑體" size="5" color="#7f0000"><b>關於我們</b></font></h2>
        <font face="微軟正黑體" size="4">
	富光國中發展夢想學校多年，打造校園為實現孩子夢想的地方。
	富光國中希望學生適性發展，自辦國三選修技藝學程，分別為商管、設計、農藝、餐旅學程，培養感興趣的學生一技之長，這次辦理假日夢想藝文客棧，成為學生體驗創業歷程的學習，學生自主經營，老師角色為輔導。結合當地產業，關西以農藝為主，配合學生專長發展，商管、設計、農藝、餐旅分工合作，終於可以在1/26日第一次經營。
        </font>
	</br></br>
	<%=image_tag("#{'aboutus.png'}")%>
	</br>
</div>

app/views/home/activity.html.erb
<div style="height:80px;width:850px; margin: 0 auto;"><font size="5" face="微軟正黑體">1/26開幕活動列表</font></div>

<div style="width:850px;margin: 0 auto; background-color:transparent; height:1000px;">
	<div style="width:850px;height:250px">
		<div style="float:left; height:240px; width: 80px; background-color:#ffbfbf; text-align:center;"><font color="#bf6000" size="4"><b>活動一</b></font></div>
		<div style="float:left; height:250px; width: 350px; border-left-style:solid; border-color: transparent; border-width:10px; background-color:transparent;">
			<font color="#bf6000" size="4" face="微軟正黑體"><b>戶外藝文表演</b></font></br></br>
			『活力、青春、陽光少年』行進鼓隊、客家八音舞色舞香、跆拳道勇者光芒四射、陶醉AHO AHO 舞蹈、天天都是HAPPY　ＤＡＹ、及他彈唱、大提琴、長笛表演等。
		</div>	
		<div style="float:right">
			<img name="outside" src="/assets/out1.png" width="400px" height="240px"></img>
		</div>
	</div>
        <div style="width:850px;height:250px">
		<div style="float:left; height:240px; width:80px; background-color:#ffbfbf; text-align:center;"><font color="#bf6000" size="4"><b>活動二</b></font></div>
		<div style="float:left; height:250px; width: 350px; border-left-style:solid; border-color: transparent; border-width:10px; background-color:transparent;">                        
			<font color="#bf6000" size="4" face="微軟正黑體"><b>義賣活動</b></font></br></br>
			<b>富貴茶：</b></br>孔明清檸茶、周瑜舒活茶、 關羽神氣茶、西施補氣茶、</br> 小喬輕盈茶、昭君明眸茶、關西養生茶</br></br>
			<b>智慧咖啡：</b></br>拿鐵、特調、美式、卡布奇諾</br></br>
			<b>夢想點心：</b></br>檸檬炸彈、快樂土司、平安餅、好運凍等</br></br>
		</div>  
                <div style="float:right">
                        <img name="sell" src="/assets/sell1.png" width="400px" height="240px"></img>
                </div>
        </div>        
	<div style="width:850px;height:250px">
		<div style="float:left; height:240px; width:80px; background-color:#ffbfbf; text-align:center;"><font color="#bf6000" size="4"><b>活動三</b></font></div>
		<div style="float:left; height:250px; width: 350px; border-left-style:solid; border-color: transparent; border-width:10px; background-color:transparent;">                        
                        <font color="#bf6000" size="4" face="微軟正黑體"><b>DIY</b></font></br></br>
			光明陶ＤＩＹ</br></br>
			水耕蔬菜ＤＩＹ
                </div>
                <div style="float:right">
                        <img name="diy" src="/assets/diy3.png" width="400px" height="240px"></img>
                </div>
        </div>
        <div style="width:850px;height:250px">
		<div style="float:left; height:240px; width:80px; background-color:#ffbfbf; text-align:center;"><font color="#bf6000" size="4"><b>活動四</b></font></div>
		<div style="float:left; height:250px; width: 350px; border-left-style:solid; border-color: transparent; border-width:10px; background-color:transparent;">
                        <font color="#bf6000" size="4" face="微軟正黑體"><b>花海欣賞</b></font></br></br>
                        櫻花、波斯菊、向日葵
                </div>

                <div id="div1" style="float:right">
                        <img id="pimg" name="flower" src="/assets/flower1.png" width="400px" height="240px"></img>
                </div>
        </div>

</div>
</br>
</br>

<%=image_tag("#{'edm.png'}")%>

app/views/home/dreamcoffee.html.erb
<div style="width:900px; margin: 0 auto;">

	<h2><font face="微軟正黑體" size="5" color="7f0000"><b>未來展望</b></font></h2>
    	<font face="微軟正黑體" size="4">
	&nbsp; &nbsp; 未來，富光國中將打造藝文及鄉土景點導覽教室，培養學生用中文、英文、客語來做觀光導覽，保留台三線客家文化、客家語言，留下母語，未來也有商機。可以成為遊客中心，由導覽可以學到口語表達能力，人際溝通力，熱愛鄉土情懷，培養自信…等未來人才優質活力。</br></br>
&nbsp; &nbsp; 結合學校發展地方產業，讓學生有在地情懷及創業經驗，並帶動羅馬公路的觀光及農產品行銷。學校營造環境氛圍，使學生有高度意願參與, 家長也會參與，共襄盛舉，帶動羅馬公路的活力。</br>
    	</font>
	
        <h2><font face="微軟正黑體" size="5" color="#7f0000"><b>行動咖啡車</b></font></h2>
        <font face="微軟正黑體" size="4">
	&nbsp; &nbsp; 另外，募款購買行動咖啡車，取名『夢想POWER車』捐給羅馬公路上的偏遠學校-富光國中；或與企業合作贊助，尤其是觀光餐飲業更好，互利模式。
        </font>
</div>

app/views/home/error.html.erb
請將必填資訊填上

</br>
<%= link_to "回到上一頁", new_home_path%>

app/views/home/feel.html.erb
<div style="margin: 0 auto; width:900px; height:auto">
    <h2><font face="微軟正黑體" size="5" color="7f0000"><b>課程</b></font></h2>
    <font face="微軟正黑體" size="4">
        課程部分：由師生一起指導遊客親手做光明陶藝品DIY，讓遊客體驗捏陶.燒陶.作品可帶回家紀念(富光國中有陶藝教室.設備齊全.全校師生都會做陶藝品)； 學生與外界接觸，從不同人身上學到相處的經驗。
	</br></br>
	<%=image_tag("#{'diy1.png'}")%>
	</br>
	</br>
	另有水耕蔬菜DIY,土耕蔬菜體驗.跆拳道體驗,客家八音指導等，並結合師生藝文表演、作品展覽等。
	</br>
	</br>
	<%=image_tag("#{'vega.png'}")%>

    </font>
    </br>
    </br>


</div>

app/views/home/goal.html.erb
<div style="margin: 0 auto; width:900px; height:800px">
    <font face="微軟正黑體" size="4">
    『富光夢想藝文客棧』，於寒暑假周六才舉行，希望與社區結合，發展遊客觀光休息，義賣校園富貴茶、光明陶、夢想咖啡、智慧點心 ,及戶外藝文表演、水耕蔬菜DIY活動…等，歡迎大家來作客。</br></br>
    </font>
    <h2><font face="微軟正黑體" size="5" color="7f0000"><b>活動簡介</b></font></h2>
    <font face="微軟正黑體" size="4">
    1. 在寒暑假開辦.提供單車客及重機群...遊客.休息小憩</br></br>
    2. 戶外.有Good view.技藝學程學生創業服務.提供點心.茶.咖啡等</br></br>
    3. 還可欣賞師生藝文表演.羅馬公路及關西景點導覽解說</br></br>
    4. 參加陶藝DIY.水耕蔬菜DIY.開心農場.客家八音...等自選遊學課程</br></br>
    </font>
    </br>
    </br>


  <div style="width:500px;float:left;">
    <h2><font face="微軟正黑體" size="5" color="7f0000"><b>活動目標</b></font></h2>
    <font face="微軟正黑體" size="4">
    1.讓學生有創業經驗.扶貧助學</br></br>
    2.幫忙鼓勵大家一起響應，讓捐款贊助者發光發亮，成為發財金</br></br>
    3.富有一生.光明一輩子，讓這些孩子從此能自給自足進德修業</br></br>
    4.開張時再請大家共襄盛舉</br></br>
    5.下一代需要自立自強，更需要我們的扶持</br></br>
    6.讓別人的孩子幸福，自己的孩子才會更幸福哦!</br></br>
    </font>
  </div>
  <div style="width:400px; height:500px; float:left;">
    <div style="margin-top:70px;"><%=image_tag("#{'school.png'}")%></div>
  </div>
</div>

app/views/home/index.html.erb
		                <meta http-equiv="content-type" content="text/html;charset=iso-8859-1" />
                <meta name="description" value="This continuously scrolling product slider shows the product name onMouseOver. In addition, it also has pagination bullets that centeres the product and shows its name after clicking." />
                <meta name="keywords" value="continuous, continuously, scrolling, slider, carousel, jquery" />
                <title>Cool continuously scrolling product slider</title>

                <script src="http://code.jquery.com/jquery-1.8.2.min.js" type="text/javascript"></script>
                <script src="/assets/jquery.carouFredSel-6.1.1-packed.js" type="text/javascript"></script>
                <script type="text/javascript">
                        $(function() {

                                $('#carousel').carouFredSel({
                                        width: '100%',
                                        items: {
                                                visible: 'odd+2'
                                        },
                                        scroll: {
                                                pauseOnHover: true,
                                                onBefore: function() {
                                                        $(this).children().removeClass( 'hover' );
                                                }
                                        },
                                        auto: {
                                                items: 1,
                                                easing: 'linear',
                                                duration: 1250,
                                                timeoutDuration: 0
                                        },
                                        pagination: {
                                                container: '#pager',
                                                items: 1,
                                                duration: 0.5,
                                                queue: 'last',
                                                onAfter: function() {
                                                        var cur = $(this).triggerHandler( 'currentVisible' ),
                                                                mid = Math.floor( cur.length / 2 );

                                                        cur.eq( mid ).addClass( 'hover' );
                                                }
                                        }
                                });

                        });
                </script>

	
		</br>
        <div  style="width:900px; height:630px; margin: 0 auto;">
          <%=image_tag("#{'poster.png'}")%>
        </div>
<div style="width:900px; margin: 0 auto;">
		<div id="wrapper">
			<div id="carousel">
				<div>
					<img src="/assets/1.png" alt="fruit1" width="200" height="200" />
					<span>1</span>
				</div>
				<div>
					<img src="/assets/2.png" alt="fruit2" width="200" height="200" />
					<span>2</span>
				</div>
				<div>
					<img src="/assets/3.png" alt="fruit3" width="200" height="200" />
					<span>3</span>
				</div>
				<div>
					<img src="/assets/4.png" alt="fruit4" width="200" height="200" />
					<span>4</span>
				</div>
				<div>
					<img src="/assets/5.png" alt="fruit5" width="200" height="200" />
					<span>5</span>
				</div>
				<div>
					<img src="/assets/6.png" alt="fruit6" width="200" height="200" />
					<span>6</span>
				</div>
				<div>
					<img src="/assets/7.png" alt="fruit7" width="200" height="200" />
					<span>7</span>
				</div>
				<div>
					<img src="/assets/8.png" alt="fruit8" width="200" height="200" />
					<span>8</span>
				</div>
				<div>
					<img src="/assets/9.png" alt="fruit9" width="200" height="200" />
					<span>9</span>
				</div>
				<div>
					<img src="/assets/10.png" alt="fruit10" width="200" height="200" />
					<span>10</span>
				</div>
				<div>
					<img src="/assets/11.png" alt="fruit11" width="200" height="200" />
					<span>11</span>
				</div>
				<div>
					<img src="/assets/12.png" alt="fruit12" width="200" height="200" />
					<span>12</span>
				</div>
				                                <div>
                                        <img src="/assets/13.png" alt="fruit12" width="200" height="200" />
                                        <span>13</span>
                                </div>
				                                <div>
                                        <img src="/assets/14.png" alt="fruit12" width="200" height="200" />
                                        <span>14</span>
                                </div>
				                                <div>
                                        <img src="/assets/15.png" alt="fruit12" width="200" height="200" />
                                        <span>15</span>
                                </div>
				                                <div>
                                        <img src="/assets/16.png" alt="fruit12" width="200" height="200" />
                                        <span>16</span>
                                </div>
				                                <div>
                                        <img src="/assets/17.png" alt="fruit12" width="200" height="200" />
                                        <span>17</span>
                                </div>
				                                <div>
                                        <img src="/assets/18.png" alt="fruit12" width="200" height="200" />
                                        <span>18</span>
                                </div>
                                <div>
                                        <img src="/assets/19.png" alt="fruit12" width="200" height="200" />
                                        <span>19</span>
                                </div>
                                <div>
                                        <img src="/assets/20.png" alt="fruit12" width="200" height="200" />
                                        <span>20</span>
                                </div>
			</div>
			<div id="pager"></div>
		</div>
</div>

app/views/home/new.html.erb
</br>
<div id="topicList">
  <table class="tableTopicList">
          <thead>
                  <tr>
		    <th>主題</th>
		    <th>發問者</th>
		    <th>更新時間</th>
		  </tr>
          </thead>
	   <tbody>
                  <% @showFeedbacks.each do |show| -%>
                          <tr>
				<td><%=link_to show.topic, home_path(show)%></td>
				<td><%=show.name%></td>
				<td><%=show.updated_at%></td>
			  </tr>
                  <% end-%>
          </tbody>
  </table>
</div>

</br>
</br>
</br>

<div id='feedbackForm'>
  <font face="微軟正黑體" size="5"><b>我有問題要問！</b></font>
  <font face="微軟正黑體">

  <%= form_tag '/home', :method=>nil  do %>

        <%= label :feedback, :name, '名稱'%>
        <%= text_field :feedback, :name, :value=>"匿名"%>

        <%= label :feedback, :phone,'電話'%>
        <%= text_field :feedback, :phone%>

        <%= label :feedback, :email,'email'%>
        <%= email_field :feedback, :email%>

        <%= label :feedback, :topic,'主題 *必填'%>
        <%= text_field :feedback, :topic%>	

        <%= label :feedback, :context, '問題 ＊必填'%>
        <%= text_area :feedback, :context%>

        <%= submit_tag '確定送出'%>
  <% end%>
  </font>
</div>

app/views/home/show.html.erb
</br>
<div id="feedback">
  <div id="feedbackTopic">
    <font size='5' face="微軟正黑體"><b><%@showFeedbackContext.name%>提到...<%=@showFeedbackContext.topic%></br></b></font>
  </div>
  <div id="feedbackContext"> 
    <%= simple_format @showFeedbackContext.context%>
  </div>
  </br>
  </br>
</div> 
<div id="answerContext">
  <font size='5' face="微軟正黑體"><b>校方回應</b></font>
    <table class="reply">
        <thead>
        </thead>
         <tbody>
                <% @showAnswerContext.each do |show| -%>
                        <tr><td></br><%= simple_format show.context %></br></br><%= show.updated_at%></td></tr>
			
                <% end-%>
        </tbody>
    </table>
</div>

</br>

<div id="discussDiv">
</br>
</br>
</br>
<font face="微軟正黑體" size="5"><b>討論</b></font>
<table class="discuss">
        <thead>
                <tr><th></th></tr>
        </thead>
         <tbody>
                <% @showDiscussContext.each do |show| -%>
                        <tr>
			  <td>
			    <font face="微軟正黑體" color="#7f4040"><b><%=show.name%>提到...</b></font>
			    </br>
			    <font face="微軟正黑體"><%=simple_format show.context%></br></br><%= show.updated_at%></font>
			    </br>
			    </br>	
			  </td>
			</tr>
                <% end-%>
        </tbody>
  </table>

  <%= form_tag '/home/savediscuss', :id=>'discuss',:method=>nil  do %>
        <%= label :discuss, :name, "稱呼"%>      
	<%= text_field :discuss, :name, :value=>"匿名"%>

        <%= label :discuss, :phone,'電話'%>
        <%= text_field :discuss, :phone%>


        <%= label :discuss, :email,'email'%>
        <%= text_field :discuss, :email%>
	
	<%= hidden_field :discuss ,:feedback_id, :value=>@id%>

        <%= label :discuss, :context, "留言"%>
        <%= text_area :discuss, :context%>

        <%= submit_tag '確定'%>
  <% end%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>夢想藝文客棧</title>


  <script type="text/javascript" src="jquery.jcoverflip.js"></script>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script>
  $(function(){
    $('#flip').jcoverflip();
 
  });
</script>
</head>
<body  onresize = "adjustWidth()" style="background-color:#FFFF99">
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=400625820030089";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <%= javascript_include_tag :defaults %>
  <div class="fb-like-box" data-href="https://www.facebook.com/hakkaspots" data-width="250" data-show-faces="true" data-stream="true" data-header="true" style="float:right; margin-top:250px;height:300px"></div>
  </div>
  <div id="all">
    <div id="back-bar">
      <ul><font face="微軟正黑體">
        <% if user_signed_in? %>
          <li><%= link_to '登出', destroy_user_session_path, :method => 'delete'%></li>
          <li><%= link_to '問題列表', new_teacher_path%></li>
          <li><%= link_to '後台主頁', teacher_index_path%></li>
        <% else %>
          <li><%= link_to '教師登入', new_user_session_path %></li>
        <% end %>
      </ul></font>
    </div>
    <div id="top">
      <div id="top-left"><%=link_to image_tag("#{'logo.png'}"), root_path%></div>
      <div id="top-right">
	<div id="top-right-briefintro">
	  <h2><b><font face="微軟正黑體" color="#7f0000">夢 &nbsp;想 &nbsp;藝 &nbsp;文 &nbsp;客 &nbsp;棧&nbsp;</font></b></h2>
	      <font face="微軟正黑體" size="3"><b>富光國中</b></font></br>
	      <font face="微軟正黑體" size="2">學校發展多年&nbsp;&nbsp;持續打造夢想學校</br>培養學生一技之長&nbsp;&nbsp;讓學生體驗創業學習的歷程</br></font>

	</div>
	<div id="top-right-bar">
	  <ul><font face="微軟正黑體">
	    <% if user_signed_in?%>
	    <% else%>
	      <li><%= link_to "聯絡我們", new_home_path%></li>
	      <li><%= link_to "關於我們", home_aboutus_path%></li>
	      <li><%= link_to "未來展望", home_dreamcoffee_path%></li>
	      <li><%= link_to "體驗課程", home_feel_path%></li>
	      <li><%= link_to "開幕活動", home_activity_path%></li>
	      <li><%= link_to "活動目標", home_goal_path%></li>
	    <%end%>
	  </ul></font>
	</div>
      </div>
    </div>
    <div id="main">
      </br>
      <%= yield %>
    </div>
    <div id="bottom">
	<font face="微軟正黑體" size="2"><b></br></br>新竹縣關西鎮東光里十六張49號　Tel:(03)5872224　Fax:(03)5877224
	</br>清華大學 DreamPocket 團隊製作         Copyright © 2013-2013</font>
    </div>
    <p align="center"><a href="http://www.voxeo.com"><img src="http://www.hot-hit-counter.com/counter?id=EA0A98DD-05EF-4C72-826A-8B4A3C5EAEC3&style=d_n-iron2,ml_6" border="0" alt="ivr"/></a></p>
    </br>
  </div>
</body>
</html>

<script>
adjustWidth();

function adjustWidth(){
  var w = 0;
  var mysize = 1000;
  if (document.body.clientWidth){
    w = document.body.clientWidth;
  }
  var allDiv = document.getElementById("all");
  var st = (w-1000)/2;
  if(st>0){
    allDiv.style.left = st+"px";
  }
}
</script>

app/views/teacher/edit.html.erb
  <%= form_tag teacher_path(@answer),:method=>:put  do %>

        <%= label :answer, :context, '回應'%>
        <%= text_area :answer, :context%>

        <%= submit_tag '確定'%>
  <% end%>

app/views/teacher/index.html.erb
teacher index

app/views/teacher/new.html.erb
teacher new

</br>
<div id="topicList">
  <table class="feedbackTopic">
          <thead>
		  <tr><th>主題</th><th>姓名</th><th>時間</th></tr>
          </thead>
           <tbody>
                  <% @showFeedbacks.each do |show| -%>
			  <tr>
                                <td><%=link_to show.topic, teacher_path(show)%></td>
                                <td><%=show.name%></td>
				<td><%=show.updated_at%></td>
                          </tr>

                  <% end-%>
          </tbody>
  </table>
</div>

app/views/teacher/show.html.erb
</br>
<div id="feedback">
  <div id="feedbackTopic">
    <font size='5' face="微軟正黑體"><b><%=@showFeedbackContext.name%>問到.....<%=@showFeedbackContext.topic%></b></font>
  </div>
  </br>
  <%=@showFeedbackContext.context%>
  </br>
  </br>
  <%= link_to 'Delete', teacher_path(@showFeedbackContext), :method => :delete%>
</div>
<div id="answerContext">
<font size='5' face="微軟正黑體"><b>校方回應</b></font>
    <table class="reply">
        <thead>
        </thead>
         <tbody>
                <% @showAnswerContext.each do |show| -%>
                        <tr>
				<td></br><%= simple_format show.context%></br></br><%=show.updated_at%><%= link_to "修改回應", edit_teacher_path(show)%></td>
			</tr>
                <% end-%>
        </tbody>
    </table>
</div>
</br>
<div id="answerField">
  <%= form_tag '/teacher',:method=>nil  do %>
        <%= hidden_field :answer, :name, :value=>"校方"%>

        <%= hidden_field :answer, :feedback_id, :value=>@id%>

        <%= label :answer, :context, '回應'%>
        <%= text_area :answer, :context%>

        <%= submit_tag '確定'%>
  <% end%>
</div>

</br>
</br>


<div id="discussDiv">
</br>
</br>
</br>
</br>
</br>
</br>
<font face="微軟正黑體" size="5"><b>回應</b></font>
<table class="discuss">
        <thead>
                <tr><th></th></tr>
        </thead>
         <tbody>
                <% @showDiscussContext.each do |show| -%>
                        <tr>
                          <td>
                            <font face="微軟正黑體" color="#7f4040"><b><%=show.name%>提到...</b></font>
                            </br>
                            <font face="微軟正黑體"><%=simple_format show.context%></br></br><%=show.updated_at%></font>
                            </br>
                            </br>       
                          </td>
                        </tr>
                <% end-%>
        </tbody>
  </table>

  <%= form_tag '/home/savediscuss', :id=>'discuss',:method=>nil  do %>
        <%= label :discuss, :name, "稱呼"%>      
        <%= text_field :discuss, :name, :value=>"富光國中"%>

        <%= hidden_field :discuss ,:feedback_id, :value=>@id%>

        <%= label :discuss, :context, "留言"%>
        <%= text_area :discuss, :context%>

        <%= submit_tag '確定'%>
  <% end%>
</div>